name: Build Windows and macOS Executables

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # 1. ADICIONADO 'openpyxl' À INSTALAÇÃO
        pip install pandas selenium webdriver-manager pyinstaller openpyxl

    - name: Build executable with PyInstaller
      run: |
        # 2. ADICIONADO O ARGUMENTO --hidden-import
        pyinstaller --onefile --windowed --name="Automacao_NFe_FSist" --hidden-import=openpyxl teste_web.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Automacao_NFe_FSist-${{ matrix.os }}
        path: dist/
